### ISSUE TITLE
Error executing the script

### ISSUE THREAD

**Issue by rohitrajan75** [bahamas10/zfs-prune-snapshots#13]
Hi team,

I'm trying to use this script, i do not have any coding experience.
my SunOS version is 11.4. when i'm running the script i got below error
# ./zfs-prune-snapshots.sh -vn 2M
./zfs-prune-snapshots.sh: line 161: %s: syntax error: operand expected (error token is "%s")

Please help to suggest what went wrong.
Thanks
Rohit

**Comment by rohitrajan75** [comment]
i resolved this problem by using date | nawk "BEGIN{print srand}" instead of date +%s
however now the problem is the human readable timestap is coming to 51 years old for every snapshot.
and even if i try to run and delete snapshots using this script the error says
cannot open ------ invalid dataset name

Please help to solve 

thanks in advance

**Comment by bahamas10** [comment]
I'm not sure what's happening here honestly.  I don't have a system where I can recreate this behavior unfortunately.

**Comment by bahamas10** [comment]
Ok, i've done some digging.  The line that throws the error appears to be calling:

    date +%s

This is used to get the current epoch time.  I'm not sure exactly what your command:

    date | nawk 'BEGIN { print srand}'

is doing.  In my testing, that will always return the number `1` one.  Since the code is using the number `1` as the epoch time, it will calculate every snapshot as being 51 years old (or more accurately, the current year minus 1970).  You'll need to modify that line to get the current epoch time... there are a couple of ways to do that, but i'd recommend trying `perl` since you said you are on SunOS.

Try replace that line with:

    now=$(perl -le 'print time')

And see if that works.  If it does, we can go from there to code a solution so it'll work for you without modification.
